config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  resources :surveys

  root "surveys#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy:true, reject_if:->(a){a['content'].blank?}
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy:true, reject_if:
      ->(attributes){ attributes['content'].blank?}
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:content, :question_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content, :survey_id)
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @survey }
    end
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).
          permit(:name, questions_attributes:[:id, :content, :_destroy,
            answers_attributes:[:id, :content, :_destroy]])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def link_to_add_fields(name, f, association)
    obj = f.object.send(association).klass.new
    id = obj.object_id
    fields = f.simple_fields_for(association, obj, child_index:id) do |builder|
      render(association.to_s.singularize, f:builder)
    end
    link_to name, '#',
            class:'add_fields',
            data:{id:id, fields:fields.gsub("\n","")}
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/answers/_form.html.haml
= simple_form_for(@answer) do |f|
  = f.error_notification

  .form-inputs
    = f.input :content
    = f.association :question

  .form-actions
    = f.button :submit

app/views/answers/edit.html.haml
.page-header
  = link_to answers_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @answer, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing answer

= render 'form'

app/views/answers/index.html.haml
.page-header
  = link_to new_answer_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Answer
  %h1 Listing answers

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Content
        %th Question
        %th
        %th
        %th

    %tbody
      - @answers.each do |answer|
        %tr
          %td= answer.content
          %td= answer.question
          %td= link_to 'Show', answer
          %td= link_to 'Edit', edit_answer_path(answer)
          %td= link_to 'Destroy', answer, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/answers/new.html.haml
.page-header
  = link_to answers_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New answer

= render 'form'

app/views/answers/show.html.haml
.page-header
  = link_to answers_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_answer_path(@answer), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show answer

%dl.dl-horizontal
  %dt Content:
  %dd= @answer.content
  %dt Question:
  %dd= @answer.question

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %title my_196_nested_form

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{:type => "button", :data => {:toggle => "collapse", :target => "#navbar"}, :aria => {:expanded => "false", :controls => "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Project name", "#", :class => "navbar-brand"
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => "#"} Home
            %li
              %a{:href => "#about"} About
            %li
              %a{:href => "#contact"} Contact
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert alert-#{%w[alert error].include?(name.to_s) ? "danger" : "success" } alert-dismissable", :role => "alert" do
          %button.close{:type => "button", :data => {:dismiss => "alert"} }
            %span{:aria => {:hidden => "true"} } &times;
            %span.sr-only Close
          = msg
      = yield

app/views/questions/_form.html.haml
= simple_form_for(@question) do |f|
  = f.error_notification

  .form-inputs
    = f.input :content
    = f.association :survey

  .form-actions
    = f.button :submit

app/views/questions/edit.html.haml
.page-header
  = link_to questions_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @question, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing question

= render 'form'

app/views/questions/index.html.haml
.page-header
  = link_to new_question_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Question
  %h1 Listing questions

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Content
        %th Survey
        %th
        %th
        %th

    %tbody
      - @questions.each do |question|
        %tr
          %td= question.content
          %td= question.survey
          %td= link_to 'Show', question
          %td= link_to 'Edit', edit_question_path(question)
          %td= link_to 'Destroy', question, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/questions/new.html.haml
.page-header
  = link_to questions_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New question

= render 'form'

app/views/questions/show.html.haml
.page-header
  = link_to questions_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_question_path(@question), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show question

%dl.dl-horizontal
  %dt Content:
  %dd= @question.content
  %dt Survey:
  %dd= @question.survey

app/views/surveys/_answer.html.haml
%fieldset
  .form-inline.form-group
    = f.input :content, as: :string, label:'Answer: '
    = f.input :_destroy, as: :hidden#, label:false, inline_label: 'remove'
    = link_to "remove", '#', class:'remove_fields'

app/views/surveys/_form.html.haml
= simple_form_for(@survey) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.simple_fields_for :questions do |builder|
      = render 'question', f:builder
    = link_to_add_fields 'Add questions',f,:questions

  .form-actions
    = f.button :submit



= debug params

app/views/surveys/_question.html.haml
%fieldset
  = f.input :content, label:'Question'
  = f.input :_destroy, as: :boolean, label:false, inline_label:'remove question'
  = f.simple_fields_for :answers do |builder|
    = render 'answer', f:builder
  = link_to_add_fields 'Add answers',f,:answers

app/views/surveys/edit.html.haml
.page-header
  = link_to surveys_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @survey, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing survey

= render 'form'

app/views/surveys/index.html.haml
.page-header
  = link_to new_survey_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Survey
  %h1 Listing surveys

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th
        %th
        %th

    %tbody
      - @surveys.each do |survey|
        %tr
          %td= survey.name
          %td= link_to 'Show', survey
          %td= link_to 'Edit', edit_survey_path(survey)
          %td= link_to 'Destroy', survey, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/surveys/new.html.haml
.page-header
  = link_to surveys_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New survey

= render 'form'

app/views/surveys/show.html.haml
.page-header
  = link_to surveys_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_survey_path(@survey), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show survey

%dl.dl-horizontal
  %dt Name:
  %dd= @survey.name

%ol
  - for question in @survey.questions
    %li
      = question.content
      %ul
        - for answer in question.answers
          %li
            = answer.content